//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using System;
    using System.Collections.Generic;
    using DAL;
    using System.Data.Linq.Mapping;
    [Table(Name = "Author")]
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int AuthorID { get; set; }
        [Column]
        public string FirstName { get; set; }
        [Column]
        public string LastName { get; set; }
        [Column]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        public virtual  AuthorBook AuthorBook { get; set; }
        public virtual ICollection<AuthorBook> AuthorBooks { get; set; }
        public List<Author> GetAllAuthor()
        {
            return AuthorDB.GetAllAuthor();
        }
        public static int CountAuthor()
        {
            return BookDB.CountRecord();
        }
    }
}
