//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using Hi_Tech_Order_Management_System.DAL;
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;

    [Table(Name = "Book")]
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Authors = new HashSet<Author>();
        }
        [Column(IsPrimaryKey = true)]
        public string ISBN { get; set; }
        [Column]
        public string Title { get; set; }
        [Column]
        public int YearPublished { get; set; }
        [Column]
        public Nullable<int> QOH { get; set; }
        [Column]
        public int CategoryID { get; set; }
        [Column]
        public int PublisherID { get; set; }
        [Column]
        public int UnitPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<AuthorBook> AuthorBooks { get; set; }
        public AuthorBook AuthorBook { get; set; }
        
        public bool IsUniqueId(string isbn)
        {
            return BookDB.IsUniqueId(isbn);
        }
        public static int CountBook()
        {
            return BookDB.CountRecord();
        }
    }
}
