//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using Hi_Tech_Order_Management_System.DAL;
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.OrderLines = new HashSet<OrderLine>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        public  List<Employee> SearchEmployee(string input)
        {
            return EmployeeDB.SearchRecord(input);
        }
        public  Employee SearchEmployee(int eId)
        {
            return EmployeeDB.SearchRecord(eId);
        }
        public void UpdateEmployee(Employee empUpdated)
        {
            EmployeeDB.UpdateRecord(empUpdated);
        }
        public void DeleteEmployee(int eId)
        {
            EmployeeDB.DeleteRecord(eId);
        }
        public bool IsUniqueEmployeeId(int eId)
        {
            return EmployeeDB.IsUniqueId(eId);
        }
        public static List<Employee> GetEmployeeList()
        {
            return EmployeeDB.GetAllRecords();
        }
        public void SaveEmployee(Employee employee)
        {
            EmployeeDB.SaveRecord(employee);
        }
    }
}
