//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    using Hi_Tech_Order_Management_System.DAL;
    [Table(Name = "Job")]
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Employees = new HashSet<Employee>();
        }
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int JobID { get; set; }
        [Column]
        public string JobTitle { get; set; }
        [Column]
        public decimal Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        
        public List<Job> GetJobList()
        {
            return JobDB.GetAllRecords();
        }
        public void SaveJob(Job job)
        {
            JobDB.SaveRecord(job);
        }
    }
}
