//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    using Hi_Tech_Order_Management_System.DAL;
    [Table(Name = "Order")]
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int OrderID { get; set; }
        [Column]
        public int CustomerID { get; set; }
        [Column]
        public System.DateTime OrderDate { get; set; }
        [Column]
        public string OrderType { get; set; }
        [Column]
        public string PayMethod { get; set; }
        [Column]
        public int Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public static  List<Order> GetOrderList() 
        {
            return OrderDB.GetAllRecord();
        }
    }
}
