//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderID { get; set; }
        public int QuantitySold { get; set; }
        public int EmployeeID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
