//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.BLL
{
    using Hi_Tech_Order_Management_System.DAL;
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public  List<UserAccount> GetUserList()
        {
            return UserDB.GetAllRecords();
        }

        public void SaveUser(UserAccount user)
        {
            UserDB.SaveRecord(user);
        }
        
        public void UpdateUser(UserAccount user)
        {
            UserDB.UpdateRecord(user);
        }
        public bool IsUniqueUserId(int userId)
        {
            return UserDB.IsUniqueId(userId);   
        }
        
        public void DeleteUser(int uId)
        {
            UserDB.DeleteRecord(uId);
        }
        
        public  List<UserAccount> SearchUser(string input)
        {
            return UserDB.SearchRecord(input);
        }
        public  UserAccount SearchUser(int userid)
        {
            return UserDB.SearchRecord(userid);
        }
    }
}
